version: '3.8'

services:
  terminal-server:
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - "3000:3000"
    environment:
      - DEBUG=true
      - PORT=3000
      - SESSION_TIMEOUT=3600
      - USE_AUTH=false
    volumes:
      - ./user_data:/app/user_data
      - ./logs:/app/logs
    restart: unless-stopped
